"""Loader for the (actor_label, MITRE technique) -> Intelligence-page copy mapping."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field


DEFAULT_MITRE_CATALOG_PATH = Path(__file__).with_name("mitre_technique_names.json")


class IssueFixEntry(BaseModel):
    """Intelligence-page copy for one (actor_label, MITRE technique) pair."""

    title: str = Field(min_length=1)
    recommended_fix: str = Field(min_length=1)
    impact: str = Field(min_length=1)

    model_config = ConfigDict(extra="forbid")


class IssuePlaybook(BaseModel):
    """Editable YAML document mapping actor/technique pairs to issue copy."""

    mitre_technique_names: dict[str, str] = Field(default_factory=dict)
    actor_label_names: dict[str, str] = Field(default_factory=dict)
    fixes: dict[str, dict[str, IssueFixEntry]] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")

    def fix_for(self, actor_label: str, mitre_tag: str) -> IssueFixEntry | None:
        """Return the curated fix for this pair, if one has been written."""
        return self.fixes.get(actor_label, {}).get(mitre_tag)

    def actor_label_display(self, actor_label: str) -> str:
        """Return a readable label, falling back to a title-cased actor_label."""
        return self.actor_label_names.get(actor_label, actor_label.replace("_", " ").title())


def load_issue_playbook(path: str | Path) -> IssuePlaybook:
    """Load and validate the issue playbook YAML document."""
    with open(path, encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or {}
    return IssuePlaybook.model_validate(raw)


@lru_cache(maxsize=8)
def load_mitre_technique_catalog(path: str | Path = DEFAULT_MITRE_CATALOG_PATH) -> dict[str, str]:
    """Load the full MITRE ATT&CK technique id -> name catalog, if present.

    Generated by scripts/sync_mitre_technique_names.py. Returns an empty dict
    if it hasn't been generated yet, so name lookups simply fall back to the
    rule playbook's curated names (or the bare id).

    Cached: this is called on every persona-analytics request and every
    issue sync, re-reading and re-parsing the same static ~26KB file each
    time for no reason -- the catalog only changes when
    scripts/sync_mitre_technique_names.py is re-run, which happens outside
    the running process, not per-request. Callers only ever read from the
    returned dict, never mutate it, so sharing the cached object is safe.
    """
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}
